# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    # - $HOME/.sbt
    # - $HOME/.cache/pip

language: scala
script: bin/run-ci
jdk: oraclejdk8
scala: 2.11.7

# codecov
# before_install: pip install --user codecov
# after_success: codecov
