# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/pants
    - $HOME/.sbt
    - $HOME/.zinc
    - $HOME/.cache/pip
    - $HOME/.cache/pants
    - .cache
    - .pants.d

# Taken from the pantsbuild/pants .travis.yml.
before_cache:
  - find build-support -name "*.py[co]" -print -delete
  - find $HOME/.ivy2/pants -type f -name "ivydata-*.properties" -print -delete
  - rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}

language: scala
script: ./pants run :test
jdk: oraclejdk8
scala: 2.11.7

# codecov
# before_install: pip install --user codecov
# after_success: codecov
